schema_version: 1

context:
  version: "1.11.8"

package:
  name: ghorg
  version: ${{ version }}

source:
  url: https://github.com/gabrie30/ghorg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 928f0ddb92a62295a9bdc8dc68fe4fca80991a1c410e2392011dc2c4b04f83f6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo' ) }}
    - go-licenses

tests:
  - script:
      - ghorg --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Quickly clone an entire org's or user's repositories into one directory
  homepage: https://github.com/gabrie30/ghorg
  repository: https://github.com/gabrie30/ghorg

extra:
  recipe-maintainers:
    - danielnachun
