schema_version: 1

context:
  version: "1.11.10"

package:
  name: ghorg
  version: ${{ version }}

source:
  url: https://github.com/gabrie30/ghorg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4135ccc8fc3ea1f606fcc5bd817e01a169a23e05865f4e4081f2c98c21653908

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo' ) }}
    - go-licenses

tests:
  - script:
      - ghorg --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Quickly clone an entire org's or user's repositories into one directory
  homepage: https://github.com/gabrie30/ghorg
  repository: https://github.com/gabrie30/ghorg

extra:
  recipe-maintainers:
    - danielnachun
