schema_version: 1

context:
  version: "1.11.11"

package:
  name: ghorg
  version: ${{ version }}

source:
  url: https://github.com/gabrie30/ghorg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a7970baf8b80b1968a81607f21adc6b19c6febf322889fc3a10f59cb3dfd2cb6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo' ) }}
    - go-licenses

tests:
  - script:
      - ghorg --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: Quickly clone an entire org's or user's repositories into one directory
  homepage: https://github.com/gabrie30/ghorg
  repository: https://github.com/gabrie30/ghorg

extra:
  recipe-maintainers:
    - danielnachun
